[package]
name = "rupture_os"
version = "0.1.0"
authors = ["Jade Lynn Masker <jadelynn@masker.family>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.6.4"
rust_decimal = "1.9.0"